//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTravelPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_master
    {
        public bus_master()
        {
            this.busschedule_master = new HashSet<busschedule_master>();
        }
    
        public decimal BUS_ID { get; set; }
        public string BUS_NO { get; set; }
        public Nullable<decimal> BUS_TYPE { get; set; }
        public Nullable<decimal> SOURCE_STATION { get; set; }
        public Nullable<decimal> DESTINATION_STATION { get; set; }
    
        public virtual bustype_master bustype_master { get; set; }
        public virtual station_master station_master { get; set; }
        public virtual station_master station_master1 { get; set; }
        public virtual ICollection<busschedule_master> busschedule_master { get; set; }
    }
}
