//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTravelPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class busschedule_master
    {
        public busschedule_master()
        {
            this.booking_master = new HashSet<booking_master>();
        }
    
        public decimal SCHEDULE_ID { get; set; }
        public Nullable<decimal> BUS_ID { get; set; }
        public Nullable<System.DateTime> DEPARTURE_TIME { get; set; }
        public Nullable<System.DateTime> ARRIVAL_TIME { get; set; }
        public Nullable<int> SEAT_AVAILABILITY { get; set; }
    
        public virtual ICollection<booking_master> booking_master { get; set; }
        public virtual bus_master bus_master { get; set; }
    }
}
