//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTravelPlanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelConnection : DbContext
    {
        public TravelConnection()
            : base("name=TravelConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking_master> booking_master { get; set; }
        public virtual DbSet<bus_master> bus_master { get; set; }
        public virtual DbSet<busschedule_master> busschedule_master { get; set; }
        public virtual DbSet<bustype_master> bustype_master { get; set; }
        public virtual DbSet<station_master> station_master { get; set; }
        public virtual DbSet<user_registration> user_registration { get; set; }
    }
}
